---
apiVersion: v1
kind: Service
metadata:
  name: ndk-dashboard-service
  namespace: default
  labels:
    app: ndk-dashboard
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: ndk-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: ndk-dashboard-loadbalancer
  namespace: default
  labels:
    app: ndk-dashboard
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: ndk-dashboard